### ISSUE TITLE
how add custom icon ?

### ISSUE THREAD

**Issue by ebdm13** [UN-GCPDS/qt-material#66]
I would like add custom icon like this:
![cutsom_icon](https://user-images.githubusercontent.com/60709615/178497975-a203ae9e-5338-4f06-b5ea-36a37dde267e.png)

but, as you can see, they don't have the same color as the theme

my stylesheet look like this:

```css
.is_toggled::indicator:checked{{
	image: url(src/icons/toggle_on.svg)
}}

.is_toggled::indicator:unchecked{{
	image: url(src/icons/toggle_off.svg)
}}
```

but there are no fill and stroke property for manage svg colors 😢 

and I added the menu icons like this:
```py
self.add_profile = QAction(QIcon("src/icons/add_profile.svg"), "Add Profile", self)
self.add_profile.triggered.connect(self.open_profile)
self.change_mail_bot = QAction(QIcon("src/icons/mail.svg"), "Change Mail Bot", self)
```

someone have an idea for a way to do this ?
maybe try to do with the replace_color funcion in ResourseGenerator class ?
