### ISSUE TITLE
Foreground text too dark in widgets without focus (dark-teal theme)

### ISSUE THREAD

**Issue by nicoddemus** [UN-GCPDS/qt-material#85]
Hi,

First of all thanks for the excellent package!

When upgrading to `2.14`, I noticed a difference in appearance which I'm not sure was intended.

Here are two controls in `2.12`, using the `dark-teal` theme:

(appearance does not change with focus)

![image](https://user-images.githubusercontent.com/1085180/218610730-22e07026-6c5a-4d0f-a9ba-e2bb985ce72e.png)

Here are the same controls in `2.14`:

(1st control with focus)
![image](https://user-images.githubusercontent.com/1085180/218610450-b753c0e4-6034-4f2b-9af6-8e2f1447f88d.png)

(2nd control with focus)
![image](https://user-images.githubusercontent.com/1085180/218610472-18a87e8c-e1b4-4673-9ee6-811d27c4bb73.png)

Seems like there was an attempt to make it more obvious which control has focus, however the dark foreground against the dark gray background makes the text hard to read.

Here is the same example using the `light_teal` theme:

![image](https://user-images.githubusercontent.com/1085180/218611137-df415ebd-fd37-46f8-882d-9107644bbd98.png)

Here the black text is fine, as it is easy to read against the white background.

Thanks!

---

Here is the example code I'm using:

```python
from PyQt6.QtWidgets import (
    QApplication,
    QLineEdit,
    QWidget,
    QComboBox,
    QVBoxLayout,
)

from qt_material import apply_stylesheet


app = QApplication([])

apply_stylesheet(app, theme="dark_teal.xml")

widget = QWidget()
layout = QVBoxLayout(widget)

combo = QComboBox()
combo.insertItems(0, ["Foo", "Bar"])

layout.addWidget(QLineEdit("Hello"))
layout.addWidget(combo)

widget.show()

app.exec()
```

**Comment by gustavo-iniguez-goya** [comment]
this was caused by these changes:

https://github.com/UN-GCPDS/qt-material/commit/cb1375407e896fc62d8fbbdb72121308ca5c23e9#diff-984d4227486f16ddd0bb89d5b9abc9642192955b3bb9d17de6841ea7ce3c6fe5L142-L147

https://github.com/UN-GCPDS/qt-material/commit/cb1375407e896fc62d8fbbdb72121308ca5c23e9#diff-984d4227486f16ddd0bb89d5b9abc9642192955b3bb9d17de6841ea7ce3c6fe5L183-L189

In my opinion the current behaviour is more correct, but certainly it can be improved.

**Comment by gustavo-iniguez-goya** [comment]
What about:

```css
--- qt-material/qt_material/material.css.template	2023-02-14 12:03:10.018225416 +0100
+++ lib/python3.11/site-packages/qt_material/material.css.template	2023-02-14 12:06:05.703383420 +0100
@@ -142,7 +142,8 @@
 QListView,
 QLineEdit,
 QComboBox {
-  color: {{primaryTextColor}};
+  background-color: {{secondaryColor}};
+  border-width: 0 0 2px 0;
   padding-left: {{16|density(density_scale)}}px;
   border-radius: 0px;
   border-radius: 0px;
@@ -187,10 +188,17 @@
 /*  ------------------------------------------------------------------------  */
 /*  QComboBox  */
 
+QLineEdit,
+QPlainTextEdit,
+QTextEdit,
 QDateEdit,
+QSpinBox,
+QDoubleSpinBox,
 QComboBox {
-  color: {{primaryTextColor}};
+  color: {{primaryColor|opacity(0.5)}};
   border: 2px solid {{primaryColor}};
+  border-width: 0 0 2px 0;
+  background-color: {{secondaryColor|opacity(0.3)}};
   border-radius: 0px;
   border-top-left-radius: 4px;
   border-top-right-radius: 4px;
@@ -1381,6 +1389,8 @@
 QDateTimeEdit:focus,
 QSpinBox:focus,
 QDoubleSpinBox:focus,
+QPlainTextEdit:focus,
+QTextEdit:focus,
 QLineEdit:focus,
 QComboBox:focus {
   color: {{primaryColor}};
```
